apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: train-mongo
  name: {{ .Values.dbNamespace.name }} 
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appNamespace.name }} 
  labels:
    app: train-app
    istio-injection: enabled
