apiVersion: v1
kind: Service
metadata:
  name: ts-user-mongo 
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017
  selector:
   app: ts-user-mongo 

---
apiVersion: v1
kind: Service
metadata:
  name: ts-auth-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017
  selector:
   app: ts-auth-mongo

---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017  
  selector:
   app: ts-route-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017  
  selector:
   app: ts-contacts-mongo
---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017  
  selector:
   app: ts-order-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017  
  selector:
   app: ts-order-other-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-config-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-config-mongo    

---

apiVersion: v1
kind: Service
metadata:
  name: ts-station-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-station-mongo   

---

apiVersion: v1
kind: Service
metadata:
  name: ts-train-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-train-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-travel-mongo  

---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-travel2-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-price-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-price-mongo    

---

apiVersion: v1
kind: Service
metadata:
  name: ts-security-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017  
  selector:
   app: ts-security-mongo  

---

apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-inside-payment-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-payment-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-payment-mongo
  
---

apiVersion: v1
kind: Service
metadata:
  name: ts-assurance-mongo
  namespace: train-mongo
spec:  
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-assurance-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-ticket-office-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-ticket-office-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-voucher-mysql
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 3306  
  selector:
   app: ts-voucher-mysql

---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-map-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017  
  selector:
   app: ts-food-map-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-consign-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-consign-price-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-mongo
  namespace: train-mongo
spec:
  ports:
    - name: http
      port: 27017    
  selector:
   app: ts-food-mongo
---
apiVersion: v1

kind: Service

metadata:

  name: ts-admin-basic-info-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18767

  selector:

   app: ts-admin-basic-info-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-admin-order-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16112

  selector:

   app: ts-admin-order-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-admin-route-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16113

  selector:

   app: ts-admin-route-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-admin-travel-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16114

  selector:

   app: ts-admin-travel-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-admin-user-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16115

  selector:

   app: ts-admin-user-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-assurance-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18888

  selector:

   app: ts-assurance-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-basic-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 15680

  selector:

   app: ts-basic-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-cancel-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18885

  selector:

   app: ts-cancel-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-config-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 15679

  selector:

   app: ts-config-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-consign-price-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16110

  selector:

   app: ts-consign-price-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-consign-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16111

  selector:

   app: ts-consign-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-contacts-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12347

  selector:

   app: ts-contacts-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-execute-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12386

  selector:

   app: ts-execute-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-food-map-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18855

  selector:

   app: ts-food-map-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-food-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18856

  selector:

   app: ts-food-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-inside-payment-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18673

  selector:

   app: ts-inside-payment-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-user-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12342

  selector:

   app: ts-user-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-notification-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 17853

  selector:

   app: ts-notification-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-news-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12862

  selector:

   app: ts-news-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-order-other-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12032

  selector:

   app: ts-order-other-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-order-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12031

  selector:

   app: ts-order-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-payment-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 19001

  selector:

   app: ts-payment-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-preserve-other-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 14569

  selector:

   app: ts-preserve-other-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-preserve-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 14568

  selector:

   app: ts-preserve-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-price-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16579

  selector:

   app: ts-price-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-rebook-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18886

  selector:

   app: ts-rebook-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-route-plan-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 14578

  selector:

   app: ts-route-plan-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-route-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 11178

  selector:

   app: ts-route-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-seat-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 18898

  selector:

   app: ts-seat-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-security-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 11188

  selector:

   app: ts-security-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-auth-service

  namespace: train-app

spec:

  type: LoadBalancer

  ports:

    - name: http

      port: 12340

  selector:

   app: ts-auth-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-station-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12345

  selector:

   app: ts-station-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-ticket-office-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16108

  selector:

   app: ts-ticket-office-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-ticketinfo-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 15681

  selector:

   app: ts-ticketinfo-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-train-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 14567

  selector:

   app: ts-train-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-travel2-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 16346

  selector:

   app: ts-travel2-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-travel-plan-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 14322

  selector:

   app: ts-travel-plan-service



---



apiVersion: v1

kind: Service

metadata:

  name: ts-travel-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 12346

  selector:

   app: ts-travel-service





---



apiVersion: v1

kind: Service

metadata:

  name: ts-verification-code-service

  namespace: train-app

spec:

  ports:

    - name: http

      port: 15678

  selector:
   app: ts-verification-code-service
---

apiVersion: v1
kind: Service
metadata:
  name: ts-voucher-service
  namespace: train-app
spec:
  ports:
    - name: http
      port: 16101
  selector:
   app: ts-voucher-service

