apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsUserMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsUserMongoService.servicePort }}
  selector:
   app: {{ .Values.tsUserMongoService.label.app }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAuthMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAuthMongoService.servicePort }}
  selector:
   app: {{ .Values.tsAuthMongoService.label.app }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsRouteMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsRouteMongoService.servicePort }}
  selector:
   app: {{ .Values.tsRouteMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsContactsMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsContactsMongoService.servicePort }}
  selector:
   app: {{ .Values.tsContactsMongoService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsOrderMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsOrderMongoService.servicePort }}
  selector:
   app: {{ .Values.tsOrderMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsOrderOtherMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsOrderOtherMongoService.servicePort }}
  selector:
   app: {{ .Values.tsOrderOtherMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsConfigMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsConfigMongoService.servicePort }}
  selector:
   app: {{ .Values.tsConfigMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsStationMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsStationMongoService.servicePort }}
  selector:
   app: {{ .Values.tsStationMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTrainMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTrainMongoService.servicePort }}
  selector:
   app: {{ .Values.tsTrainMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTravelMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTravelMongoService.servicePort }}
  selector:
   app: {{ .Values.tsTravelMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTrain2MongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTrain2MongoService.servicePort }}
  selector:
   app: {{ .Values.tsTrain2MongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsPriceMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsPriceMongoService.servicePort }}
  selector:
   app: {{ .Values.tsPriceMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsSecurityMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsSecurityMongoService.servicePort }}
  selector:
   app: {{ .Values.tsSecurityMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsInsidePaymentMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsInsidePaymentMongoService.servicePort }}
  selector:
   app: {{ .Values.tsInsidePaymentMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsPaymentMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsPaymentMongoService.servicePort }}
  selector:
   app: {{ .Values.tsPaymentMongoService.label.app }}
  
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAssuranceMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:  
  ports:
    - name: http
      port: {{ .Values.tsAssuranceMongoService.servicePort }}
  selector:
   app: {{ .Values.tsAssuranceMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTicketOfficeMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTicketOfficeMongoService.servicePort }}
  selector:
   app: {{ .Values.tsTicketOfficeMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsVoucherMysqlService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsVoucherMysqlService.servicePort }}
  selector:
   app: {{ .Values.tsVoucherMysqlService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsFoodMapMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsFoodMapMongoService.servicePort }}
  selector:
   app: {{ .Values.tsFoodMapMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsConsignMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsConsignMongoService.servicePort }}
  selector:
   app: {{ .Values.tsConsignMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsConsignPriceMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsConsignPriceMongoService.servicePort }}
  selector:
   app: {{ .Values.tsConsignPriceMongoService.label.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsFoodMongoService.name }}
  namespace: {{ .Values.dbNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsFoodMongoService.servicePort }}
  selector:
   app: {{ .Values.tsFoodMongoService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAdminBasicInfoService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAdminBasicInfoService.servicePort }}
  selector:
   app: {{ .Values.tsAdminBasicInfoService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAdminOrderService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAdminOrderService.servicePort }}
  selector:
   app: {{ .Values.tsAdminOrderService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAdminRouteService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAdminRouteService.servicePort }}
  selector:
   app: {{ .Values.tsAdminRouteService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAdminTravelService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAdminTravelService.servicePort }}
  selector:
   app: {{ .Values.tsAdminTravelService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAdminUserService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAdminUserService.servicePort }}
  selector:
   app: {{ .Values.tsAdminUserService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAssuranceService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAssuranceService.servicePort }}
  selector:
   app: {{ .Values.tsAssuranceService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsBasicService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsBasicService.servicePort }}
  selector:
   app: {{ .Values.tsBasicService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsCancelService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsCancelService.servicePort }}
  selector:
   app: {{ .Values.tsCancelService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsConfigService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsConfigService.servicePort }}
  selector:
   app: {{ .Values.tsConfigService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsConsignPriceService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsConsignPriceService.servicePort }}
  selector:
   app: {{ .Values.tsConsignPriceService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsConsignService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsConsignService.servicePort }}
  selector:
   app: {{ .Values.tsConsignService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsContactsService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsContactsService.servicePort }}
  selector:
   app: {{ .Values.tsContactsService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsExecuteService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsExecuteService.servicePort }}
  selector:
   app: {{ .Values.tsExecuteService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsFoodMapService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsFoodMapService.servicePort }}
  selector:
   app: {{ .Values.tsFoodMapService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsFoodService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsFoodService.servicePort }}
  selector:
   app: {{ .Values.tsFoodService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsInsidePaymentService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsInsidePaymentService.servicePort }}
  selector:
   app: {{ .Values.tsInsidePaymentService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsUserService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsUserService.servicePort }}
  selector:
   app: {{ .Values.tsUserService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsNotificationService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsNotificationService.servicePort }}
  selector:
   app: {{ .Values.tsNotificationService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsNewsService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsNewsService.servicePort }}
  selector:
   app: {{ .Values.tsNewsService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsOrderOtherService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsOrderOtherService.servicePort }}
  selector:
   app: {{ .Values.tsOrderOtherService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsOrderService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsOrderService.servicePort }}
  selector:
   app: {{ .Values.tsOrderService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsPaymentService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsPaymentService.servicePort }}
  selector:
   app: {{ .Values.tsPaymentService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsPreserveOtherService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsPreserveOtherService.servicePort }}
  selector:
   app: {{ .Values.tsPreserveOtherService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsPreserveService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsPreserveService.servicePort }}
  selector:
   app: {{ .Values.tsPreserveService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsPriceService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsPriceService.servicePort }}
  selector:
   app: {{ .Values.tsPriceService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsRebookService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsRebookService.servicePort }}
  selector:
   app: {{ .Values.tsRebookService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsRouteplanService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsRouteplanService.servicePort }}
  selector:
   app: {{ .Values.tsRouteplanService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsRouteService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsRouteService.servicePort }}
  selector:
   app: {{ .Values.tsRouteService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsSeatService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsSeatService.servicePort }}
  selector:
   app: {{ .Values.tsSeatService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsSecurityService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsSecurityService.servicePort }}
  selector:
   app: {{ .Values.tsSecurityService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAuthService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.tsAuthService.servicePort }}
  selector:
   app: {{ .Values.tsAuthService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsStationService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsStationService.servicePort }}
  selector:
   app: {{ .Values.tsStationService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTicketOfficeService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTicketOfficeService.servicePort }}
  selector:
   app: {{ .Values.tsTicketOfficeService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTicketinfoService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTicketinfoService.servicePort }}
  selector:
   app: {{ .Values.tsTicketinfoService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTrainService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTrainService.servicePort }}
  selector:
   app: {{ .Values.tsTrainService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTravel2Service.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTravel2Service.servicePort }}
  selector:
   app: {{ .Values.tsTravel2Service.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTravelPlanService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTravelPlanService.servicePort }}
  selector:
   app: {{ .Values.tsTravelPlanService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsTravelService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsTravelService.servicePort }}
  selector:
   app: {{ .Values.tsTravelService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsVerificationCodeService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsVerificationCodeService.servicePort }}
  selector:
   app: {{ .Values.tsVerificationCodeService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsVoucherService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsVoucherService.servicePort }}
  selector:
   app: {{ .Values.tsVoucherService.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsUiDashboard.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  type: {{ .Values.tsUiDashboard.serviceType }}
  ports:
    - name: http
      port: {{ .Values.tsUiDashboard.servicePort }}
      nodePort: {{ .Values.tsUiDashboard.nodePort }}
  selector:
   app: {{ .Values.tsUiDashboard.label.app }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tsAvatarService.name }}
  namespace: {{ .Values.appNamespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.tsAvatarService.servicePort }}
  selector:
   app: {{ .Values.tsAvatarService.label.app }}

